"""empty message

Revision ID: 031fbcca6695
Revises: 7479b96123f7
Create Date: 2025-07-07 23:53:27.634207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031fbcca6695'
down_revision = '7479b96123f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
